### ISSUE TITLE
Rottexpr: Windows Binaries

### ISSUE THREAD

**Issue by MasterO2** [LTCHIPS/rottexpr#22]
Please create Windows binaries for Rottexpr.

Edit (7/23/2020): Windows binaries now created. Issue has been closed by me.

**Comment by LTCHIPS** [comment]
Thanks for reminding me. I've uploaded a "release" build onto the github page.

**Comment by MasterO2** [comment]
> 
> 
> Thanks for reminding me. I've uploaded a "release" build onto the github page.

One other question: When you say additional gameplay options, are those enabled by default or do you have to enable them yourself?  Can you just play the game vanilla-style?

**Comment by LTCHIPS** [comment]
By default, rottexpr is set to provide a vanilla experience (no auto-aiming missile weapons, no random chance of guards dropping an extra pistol, no ammo pickups, etc). You'll have to enable the new gameplay options yourself. 

Most of the gameplay options can be enabled while a game is in progress, but I'd refrain from turning on zomrott in the middle of a game, as it will probably not function correctly.
