### ISSUE TITLE
Windows Binary Doesn't Launch

### ISSUE THREAD

**Issue by thevelcrosasquatch** [LTCHIPS/rottexpr#31]
Is there a specific launch command or requirement other than the core game files?
The exe doesn't launch and theres no crash errors.

**Comment by MasterO2** [comment]
> 
> 
> Is there a specific launch command or requirement other than the core game files?
> The exe doesn't launch and theres no crash errors.


If you have the GOG edition of ROTT and have the files in the correct place for rottexpr to detect them, are you then double clicking on the rottexpr **site license** executable?

**Comment by thevelcrosasquatch** [comment]
Yeah, I did try that but it didn't seem to do anything.
I also tried Commercial as the Readme stated.
A bit baffled as SDL ROTT launches but not this one.
I've tried re-installing multiple times
For one I tried moving the Steam installation to just moving the core files.
Regardless it never starts and the only messages I get are messages to put the dlls in there if they aren't.
I was just hoping I was doing something wrong but it just appears to an issue on my end.

**Comment by elvisish** [comment]
I couldn't get it working until I added exactly the files required, there's definitely some sort of weird detection issue going on if you don't have the folder set-up identically to this:
![image](https://user-images.githubusercontent.com/16231628/89736929-18bfda80-da65-11ea-9444-6c7d4ba8ebd4.png)

**Comment by thevelcrosasquatch** [comment]
> I couldn't get it working until I added exactly the files required, there's definitely some sort of weird detection issue going on if you don't have the folder set-up identically to this:

That did it!
Thanks for your help.

**Comment by elvisish** [comment]
No problem, someone from Discord (not sure if they're here?) helped me with it, I can't take any credit! It is an issue though, I'm not quite sure what Rottexpr is expecting the folder structure to resemble.
